### PR TITLE
Properly handle abnormal booleans

### PR DESCRIPTION
**Pull request by GraxCode**

### CODE REVIEW

**Comment by leibnitz27** [comment]
The reason for 'BADBOOL 3' was because this is _usually_ found when CFR has incorrectly determined that something is boolean when it's actually an integer - i.e. it's a last gasp "clearly made the wrong typing decision, but I don't want you to lose that the value really was a 3".

This change discards information - have you got an example where it's happening?

**Comment by GraxCode** [comment]
[boolean-minus-one.jar.txt](https://github.com/leibnitz27/cfr/files/4732763/boolean-minus-one.jar.txt)
Boolean with value -1 is `true`, also tested with 2,3 and other positive integers.

**Comment by GraxCode** [comment]
You could also interpret booleans that are not 0 or 1 as "X != 0", if you want to keep the information about which number it is

**Comment by leibnitz27** [comment]
I like that - let's turn badbool into != 0.  Do you want to do it?

**Pull request merged**
