### PR TITLE
add --outputencoding flag,supports saving decompiled files with specified encoding

### PR DESCRIPTION
**Pull request by passedbylove**
add --outputencoding flag,supports saving decompiled files with specified encoding for non-english speaking country.

eg. --outputencoding UTF-8

### CODE REVIEW

**Comment by passedbylove** [comment]
modern operation system were using Unicode Character Table,in my opion,saving decompiled class with utf-8 character will be the good choise.

**Comment by x4e** [comment]
Would it be better to store the charset as an instance of java.nio.charset.Charset rather than a String?

**Comment by passedbylove** [comment]
hi guy,acrodding to your suggesting ,i've found that signature
`BufferedWriter(OutputStreamWriter, java.nio.Charset)) ` will not need try-catch block, besides this, are there any deiffrent between
`BufferedWriter(OutputStreamWriter, java.nio.Charset))` and `BufferedWriter(OutputStreamWriter, String))` ?

**Comment by passedbylove** [comment]
> Would it be better to store the charset as an instance of java.nio.charset.Charset rather than a String?

hi guy,acrodding to your suggesting ,i've found that signature
`BufferedWriter(OutputStreamWriter, java.nio.Charset)) ` will not need try-catch block, besides this, are there any deiffrent between
`BufferedWriter(OutputStreamWriter, java.nio.Charset))` and `BufferedWriter(OutputStreamWriter, String))` ?

**Comment by leibnitz27** [comment]
Seems reasonable, thanks; as x4e says, minor optimisation as Charset, but in the grand scheme of things it's hardly the biggest efficiency offender, can be tweaked ;)

**Pull request merged**
