### PR TITLE
Missing quotes

### PR DESCRIPTION
**Pull request by GraxCode**

### CODE REVIEW

**Comment by Marcono1234** [comment]
Oh, I always thought this was intended to prevent recompiling it and make you aware that there was a decompilation failure.
Would it be possible to highlight this issue better then (e.g. add a comment as well), otherwise it just looks like a normal exception and depending on what you decompile (e.g. you decompile a decompiler) you would not even notice it.

**Comment by Col-E** [comment]
> Oh, I always thought this was intended to prevent recompiling it and make you aware that there was a decompilation failure.

From an API standpoint, I would prefer this in combination with reporting any decompile failures/exceptions in the logging sink.  _(Plugging #136 )_

**Comment by leibnitz27** [comment]
Yeah - good points.  Maybe a 'remove me' which DOES fail to compile next to it.

**Comment by leibnitz27** [comment]
(and #136 ;) )

**Comment by Marcono1234** [comment]
It also has its advantages that it emits compilable code because it probably makes navigation in that code using an IDE easier. Though fixing issue 136 and maybe (?) a comment would be useful nonetheless.

**Comment by GraxCode** [comment]
I think a //FIXME: would make it easier to highlight decompilation errors, and IMO producing runnable code (even if it throws an exception) is better than producing invalid code

**Pull request merged**
