### PR TITLE
Updated the pom.xml to allow CFR to compile to a single JAR

### PR DESCRIPTION
**Pull request by ThisIsLibra**
This change makes it possible to compile CFR into a single JAR by using "mvn clean compile assembly:single". Additionally, the XML file has been beautified.

### CODE REVIEW

**Comment by leibnitz27** [comment]
CFR doesn't have any dependencies - what does this buy you over 'mvn clean package'?
(my maven-fu is limited, honest question).

**Comment by ThisIsLibra** [comment]
My understanding of Maven isn't too great either, so I might be mistaken here, but this is what I thought:

The change allows for an additional build method, where the project is build into a JAR (including all dependencies) without the sources or Javadoc. 

Additionally, I am unable to compile the project with the command you gave, as the Javadoc does not accept the "-html5" argument that is passed to it (openjdk8 on my machine), which might be related to my machine, but I am able to compile it using the command I added in this PR.

Does that provide an answer to your question?

**Comment by leibnitz27** [comment]
Ah - ok, so this is html5 support being added for javadoc in j9.   I'd honestly prefer not to go down the 'add all dependencies' route you outline in this PR, because it implies I'm happy with dependencies, and I don't want to have the 'this dependency doesn't work in j6' conversation again and again ;)

Can you instead try dropping the '-html5' argument from the javadoc stanza in the pom?   This should then allow 'mvn package' to behave, and generate

31/07/2019  10:15           435,607 cfr-0.147-SNAPSHOT-javadoc.jar
31/07/2019  10:15           855,885 cfr-0.147-SNAPSHOT-sources.jar
31/07/2019  10:15         1,749,250 cfr-0.147-SNAPSHOT.jar

**Comment by ThisIsLibra** [comment]
That works exactly as you described it would. Would it be an idea to exclude the '-html5' tag from the POM by default? I'd love to embed this repository into AndroidProjectCreator, but Java 8 is the maximum version there, meaning that the project cannot be build without breaking other dependencies there. As the build process is automatic, changing the POM locally isn't the best idea.

I fully understand it if you do not want to make that change, and I have no problem with that. In any case, I'd like to thank you for your work on this amazing tool!

**Comment by leibnitz27** [comment]
That's fine by me.  It's a very small change, so I've just done it, save you making another PR.

**Comment by ThisIsLibra** [comment]
Thank you very much!

**Comment by leibnitz27** [comment]
FYI (not a problem) https://github.com/leibnitz27/cfr/issues/22

**Comment by leibnitz27** [comment]
Tweaked a bit further to selectively enable flag in j9+.

**Pull request closed without merging**
